api/urls.py
from . import views
from django.urls import path 

urlpatterns = [
    path('get_userdata/',views.get_userdata.as_view()),
    path('no_id/',views.no_id.as_view()),
    path('update_data/',views.update_data.as_view()),
]

myWebApps/urls.py
from django.urls import path 
from . import views
from django.views.generic import TemplateView

app_name = 'myWeb'
urlpatterns = [
    path('',views.home, name='home'),
    path('authenUser/',views.authenUser, name='authenUser'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('changepass/',views.changepass,name='changepass'),
    path('passChanged/',views.passChanged,name='passChanged'),
    path('adminHome/',views.adminHome,name='adminHome'),
    path('userPage/id=<int:user_id>',views.userPage,name='userPage'),
    path('home_package/',views.adminHome_package,name='home_package'),
    path('package_action/<int:package_id>',views.package_action, name='package_action'),
    path('new_package/',views.new_package,name="new_package"),
    path('delete_log/<int:id>',views.delete_log,name="delete_log"),
    path('expense/<int:user_id>',views.expense, name="expense"),
]

server/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('myWebApps.urls')),

]

myWebApps/models.py
from django.db import models

# Create your models here.

myWebApps/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse ,HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from api.models import UserPoints, UserLog, Package

def home(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            return HttpResponseRedirect(reverse('myWeb:adminHome'))
        else:
            user = User.objects.get(username=request.user.username)
            try:
                thisUser = UserPoints.objects.get(user=user.id)
                userlog = UserLog.objects.filter(user=user.id)
                points = thisUser.points
                log = []
                for data in userlog:
                    if(data.package_id!="-"):
                        thisPackage = Package.objects.get(package_id=data.package_id)
                        temp_data = {"id":data.id,
                                    "datetime":data.datetime,
                                    "package_id":data.package_id,
                                    "name":thisPackage.name,
                                    "points":thisPackage.points,
                                    "InEx":data.InEx}
                        log.append(temp_data)
                    else:
                        temp_data = {"id":data.id,
                                    "datetime":data.datetime,
                                    "package_id":"-",
                                    "name":"-",
                                    "points":data.points,
                                    "InEx":data.InEx}
                        log.append(temp_data)
            except:
                return render(request, 'home.html',{'points':points, 'log':log})
            else:
                return render(request, 'home.html',{'points':points, 'log':log})
                # return HttpResponseRedirect(reverse('myWeb:login'))
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def adminHome_package(request):
    if request.user.is_superuser:
        list_package = Package.objects.all()
        return render(request, 'adminHome.html',{'list_package':list_package,'package':True })
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def adminHome(request):
    if request.user.is_superuser:
        list_user = User.objects.filter(is_superuser=False)
        return render(request, 'adminHome.html',{'list_user':list_user,'package':False })
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('myWeb:home'))
    else:
        return render(request, 'login.html')
        
def authenUser(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return redirect('/')
    else:
        return render(request,'login.html',{'err': "Error, username or password is not correct"})

def logout(request):
    auth_logout(request)
    return render(request,'login.html',{'err': "Log Out Complete!"})

def changepass(request):
    if request.user.is_authenticated:
        return render(request,'changepass.html')
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def passChanged(request):
    username = request.user.username
    user = User.objects.get(username=username)
    if check_password(request.POST['Opassword'], user.password):
        if(request.POST['Npassword']==request.POST['Cpassword']):
            user.set_password(request.POST['Npassword'])
            user.save()
            user = authenticate(request, username=username, password=request.POST['Npassword'])
            auth_login(request, user)
            return HttpResponseRedirect(reverse('myWeb:home'))
        else:
            return render(request,'changepass.html',{'err':"Confirmed password does not match."})
    else:
        return render(request,'changepass.html',{'err':"Old password incorrect."})

def userPage(request,user_id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            user = User.objects.get(id=user_id)
            thisUser = UserPoints.objects.get(user=user_id)
            userlog = UserLog.objects.filter(user=user_id)
            points = thisUser.points
            log = []
            for data in userlog:
                if(data.package_id!="-"):
                    thisPackage = Package.objects.get(package_id=data.package_id)
                    temp_data = {"id":data.id,
                                "datetime":data.datetime,
                                "package_id":data.package_id,
                                "name":thisPackage.name,
                                "points":thisPackage.points,
                                "InEx":data.InEx}
                    log.append(temp_data)
                else:
                    temp_data = {"id":data.id,
                                "datetime":data.datetime,
                                "package_id":"-",
                                "name":"-",
                                "points":data.points,
                                "InEx":data.InEx}
                    log.append(temp_data)
            return render(request,'userPage.html',{'points':points,'username':user.username, 'log':log,'user_id':user_id})
        else:
            return HttpResponseRedirect(reverse('myWeb:home'))
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def package_action(request,package_id):
    if request.user.is_superuser:
        try:
            if(request.POST['save']):
                thisPackage = Package.objects.get(package_id=package_id)
                thisPackage.package_id = request.POST['package_id']
                thisPackage.name = request.POST['name']
                thisPackage.type = request.POST['type']
                thisPackage.points = request.POST['points']
                thisPackage.material = request.POST['material']
                thisPackage.save()
            else:
                Package.objects.get(package_id=package_id).delete()
        except:
            Package.objects.get(package_id=package_id).delete()
        return HttpResponseRedirect(reverse('myWeb:home_package'))
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def new_package(request):
    if request.user.is_superuser:
        try:
            Package.objects.create(package_id=request.POST['package_id'],
                                    name=request.POST['name'],
                                    type=request.POST['type'],
                                    material=request.POST['material'],
                                    points=request.POST['points'])
        except:
            return render(request,'adminHome.html',{'err':"Please Fill All Data."})
        else:
            return HttpResponseRedirect(reverse('myWeb:new_package'))
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def delete_log(request,id):
    if request.user.is_superuser:
        username = UserLog.objects.get(id=id).user
        thisUser = User.objects.get(username=username)
        thisUserPoint = UserPoints.objects.get(user=thisUser.id)
        if(UserLog.objects.get(id=id).InEx == "Income"):
            delete_points = Package.objects.get(package_id=UserLog.objects.get(id=id).package_id).points
            thisUserPoint.points = thisUserPoint.points-delete_points
            thisUserPoint.save()
        else:
            delete_points = UserLog.objects.get(id=id).points
            thisUserPoint.points = thisUserPoint.points+delete_points
            thisUserPoint.save()
        UserLog.objects.get(id=id).delete()
        return HttpResponseRedirect(reverse('myWeb:userPage', args=(),
                                    kwargs={'user_id': thisUser.id}))

    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def expense(request,user_id):
    print("12312313213")
    if request.user.is_superuser:
        thisUserPoints = UserPoints.objects.get(user=user_id)
        print("456456465")
        print(request.POST["ex_points"])
        if(thisUserPoints.points>=int(request.POST["ex_points"])):
            print("456789")
            thisUserPoints.points=thisUserPoints.points - int(request.POST['ex_points'])
            thisUserPoints.save()
            thisUser = User.objects.get(id=user_id)
            UserLog.objects.create(user=thisUser,InEx="Expense",points=int(request.POST["ex_points"]))
            return HttpResponseRedirect(reverse('myWeb:userPage', args=(),
                                                kwargs={'user_id': user_id}))
        else:
            user = User.objects.get(id=user_id)
            thisUser = UserPoints.objects.get(user=user_id)
            userlog = UserLog.objects.filter(user=user_id)
            points = thisUser.points
            log = []
            for data in userlog:
                if(data.package_id!="-"):
                    thisPackage = Package.objects.get(package_id=data.package_id)
                    temp_data = {"id":data.id,
                                "datetime":data.datetime,
                                "package_id":data.package_id,
                                "name":thisPackage.name,
                                "points":thisPackage.points,
                                "InEx":data.InEx}
                    log.append(temp_data)
                else:
                    temp_data = {"id":data.id,
                                "datetime":data.datetime,
                                "package_id":"-",

myWebApps/templates/adminHome.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:380px;
	font-size:18px;
	}
	.small {
	  width:300px;
	}
	.left {
	  float:left;
	  width:50%;
	}
	.right {
	  float:left;
	  width:50%;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}
	.rightmenu {
	  background-color: green;
	}
	.leftmenu {
		background-color: grey;
	}
	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>
	<ul>
		<li><a>Admin</a></li>
        <li style="float:right"><a class="rightmenu" href="{% url 'myWeb:logout' %}">LogOut</a></li>
        <li style="float:right"><a href="{% url 'myWeb:home' %}">{{ user.get_username }}</a></li>
				{% if package %}
					<li><a class ="leftmenu" href="{% url 'myWeb:home' %}">User</a></li>
				{% else %}
					<li><a class ="leftmenu" href="{% url 'myWeb:home_package' %}">Package</a></li>
				{% endif %}
	</ul>
	</br>
	</br>
		<fieldset class="small">
		 <legend><h2>Admin</h2></legend>
			Username: {{user.username}}<br><br>
			<form action="{% url 'myWeb:changepass' %}" method="post">
			{% csrf_token %}
				<input type="submit" value="Change Password">
			</form>
		</fieldset>
		{% if package %}
			<fieldset>
			<legend><h2>list of packages</h2></legend>
				<table border="1">
				<tr>
					<th>Package ID</th>
					<th>Name</th>
					<th>Type</th>
					<th>Material</th>
					<th>Points</th>
				</tr>
						{% for p in list_package %}
							<div style="overflow-x:auto;"></div>
							<tr>
								<form action="{% url 'myWeb:package_action' p.package_id %}" method="post">
								{% csrf_token %}
								<td><input type="text" name="package_id" placeholder={{p.package_id}} value={{p.package_id}}></td>
								<td><input type="text" name="name" placeholder={{p.name}} value={{p.name}}></td>
								<td><input type="text" name="type" placeholder={{p.type}} value={{p.type}}></td>
								<td><input type="text" name="material" placeholder={{p.material}} value={{p.material}}></td>
								<td><input type="text" name="points" placeholder={{p.points}} value={{p.points}}></td>
								<td><input type="submit" name="save" value="Save"></td>
								<td><input type="submit" name="delete" value="Delete"></td>
								</form>
							</tr>

							</div>
						</form>
						{% endfor %}
								<form action="{% url 'myWeb:new_package' %}" method="post">
								{% csrf_token %}
								<tr>
								<td><input type="text" name="package_id" placeholder="package_id"></td>
								<td><input type="text" name="name" placeholder="name"></td>
								<td><input type="text" name="type" placeholder="type"></td>
								<td><input type="text" name="material" placeholder="material"></td>
								<td><input type="text" name="points" placeholder="points"></td>
								<td><input type="submit" value="New"></td>
								</tr>
								</form>
				</table>
			</fieldset>
			{{ err }}
			</br>
		{% else %}
			<fieldset>
			<legend><h2>list of users</h2></legend>
				{% for u in list_user  %}
					<a href="{% url 'myWeb:userPage' u.id %}">{{u.username}}</a></br>
				{% endfor %}
			</fieldset>
		{% endif %}
	</body>
</html>

myWebApps/templates/changepass.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:400px;
	font-size:18px;
	}

	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}

	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>
	<ul>
	  <li><a>WebSite</a></li>
	</ul>
		<br><br><h2>{{ err }}</h2>
        <fieldset>
		<form action="{% url 'myWeb:passChanged' %}" method="post">
		{% csrf_token %}
		 <legend><h2>Change Password</h2></legend>
			Old Password: <input type="password" name="Opassword" placeholder="Old Password"><br><br>
			New Password: <input type="password" name="Npassword" placeholder="New Password"><br><br>
			Confirm Password: <input type="password" name="Cpassword" placeholder="Confirm Password"><br><br>
			<input type="submit" value="Submit">
        </form>
        <form action="{% url 'myWeb:home' %}" method="get">
			<input type="submit" value="Back">
        </form>
        </fieldset>
	</body>
</html>

myWebApps/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  margin-top: 80px;
  padding-top: 0em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:550px;
  background-color: white;


	font-size:18px;
	}
	.small {
	  width:300px;
	}
	.left {
	  float:left;
	  width:50%;
	}
	.right {
	  float:left;
	  width:50%;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}
	.rightmenu {
	  background-color: green;
	}
	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body style= " background: url(http://dcs.op.kmutnb.ac.th/images/kmutnb.jpg); background-size: cover">
	<ul>
		<li><a>myWeb</a></li>
        <li style="float:right"><a class="rightmenu" href="{% url 'myWeb:logout' %}">LogOut</a></li>
        <li style="float:right"><a>{{ user.get_username }}</a></li>
	</ul>

		<fieldset class="small">
		 <h2>Informations</h2>
			Username: {{user.username}}<br><br>
			Point(s): {{points}} <br><br>
			<form action="{% url 'myWeb:changepass' %}" method="post">
			{% csrf_token %}
				<input type="submit" value="Change Password">
			</form>
		</fieldset>
		<fieldset>
		<h2>History</h2>
				{% if log %}
					<table border="1">
					<tr>
						<th>datetime</th>
						<th>package_id</th>
						<th>package_name</th>
						<th>points</th>
						<th>In/Ex</th>
					</tr>
							{% for userLog in log %}
							<div style="overflow-x:auto;"></div>
							<tr>
								<td>{{userLog.datetime}}</td>
								<td>{{userLog.package_id}}</td>
								<td>{{userLog.name}}</td>
								<td>{{userLog.points}}</td>
								<td>{{userLog.InEx}}</td>
							</tr>
							</div>
							</form>

							{% endfor%}
					</table>
				{% else %}
					There is No History of this Account.
				{% endif %}
		</fieldset>

	</body>
</html>

myWebApps/templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:300px;
	font-size:18px;
	}

	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}

	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>
	<ul>
	  <li><a>WebSite</a></li>
	</ul>
		<br><br><h2>{{ err }}</h2>
		<form action="{% url 'myWeb:authenUser' %}" method="post">
		{% csrf_token %}
		<fieldset>
		 <legend><h2>Login</h2></legend>
			Username: <input type="text" name="username" placeholder="Username"><br><br>
			Password: <input type="password" name="password" placeholder="Password"><br><br>
			<input type="submit" value="Sign In">
		</fieldset>
	</form>
	</body>
</html>

myWebApps/templates/userPage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body {margin:0;}

	font-family: Arial;
	}

	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:550px;
	font-size:18px;
	}
	.small {
	  width:300px;
	}
	.left {
	  float:left;
	  width:50%;
	}
	.right {
	  float:left;
	  width:50%;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}
	.rightmenu {
	  background-color: green;
	}
	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: green;
	}
	</style>
</head>
	<body>
	<ul>
		<li><a>myWeb</a></li>
        <li style="float:right"><a class="rightmenu" href="{% url 'myWeb:logout' %}">LogOut</a></li>
        <li style="float:right"><a href="{% url 'myWeb:home' %}">{{ user.get_username }}</a></li>
	</ul>
	</br>
	</br>
		<fieldset class="small">
		 <legend><h2>User Informations</h2></legend>
			Username: {{username}}<br><br>
			Point(s): {{points}} <br><br>
		</fieldset>
		<fieldset>
		<legend><h2>History</h2></legend>
				{% if log %}
					<table border="1">
					<tr>
						<th>datetime</th>
						<th>package_id</th>
						<th>package_name</th>
						<th>points</th>
						<th>In/Ex</th>
					</tr>
							{% for userLog in log %}
							<div style="overflow-x:auto;"></div>
							<tr>
								<form action="{% url 'myWeb:delete_log' userLog.id %}" method="post">
								{% csrf_token %}
								<td>{{userLog.datetime}}</td>
								<td>{{userLog.package_id}}</td>
								<td>{{userLog.name}}</td>
								<td>{{userLog.points}}</td>
								<td>{{userLog.InEx}}</td>
								<td><input type="submit" name="delete" value="Delete"></td>
								</form>
							</tr>
							</div>
							{% endfor%}
					</table></br></br></br>
					{{err}}
					<form action="{% url 'myWeb:expense' user_id %}" method="post">
					{% csrf_token %}
					<input type="text" name="ex_points" placeholder="Expense Points">
					<input type="submit" value="Expense">
					</form>
				{% else %}
					There is No History of this Account.
				{% endif %}
		</fieldset>

	</body>
</html>